-- Analytics table for Cloud Peak Silver Labradors
-- Run this in the Supabase SQL Editor.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  page_path text not null,
  page_title text not null,
  referrer text,
  session_id text not null,
  properties jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id);

create index if not exists analytics_events_properties_gin_idx
  on public.analytics_events using gin (properties);

alter table public.analytics_events enable row level security;

-- Allow the public anon key used by the site to insert analytics rows.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'Allow anonymous analytics inserts'
  ) then
    create policy "Allow anonymous analytics inserts"
      on public.analytics_events
      for insert
      to anon
      with check (true);
  end if;
end $$;
